Handle circular dependency on root package (fix #118)
python-poetry/poetry-plugin-export pull request #121
Opened 2022-09-16 20:03 UTC by brechtm

A test case is still missing...

2022-09-16 20:16 UTC, dimbleby commented on src/poetry_plugin_export/walker.py
> +    root_package_name: str,
these are all `NormalizedName` (from packaging.utils)

2022-12-07 11:35 UTC, brechtm commented on src/poetry_plugin_export/walker.py
> +    root_package_name: str,
Fixed now!

2022-12-07 11:36 UTC, brechtm commented
I finally got around to adding a test case. Please review.

2022-12-18 12:31 UTC, radoering requested changes

2022-12-18 12:31 UTC, radoering commented on tests/test_exporter.py
> +                    "dependencies": {"my-package": {"version": "1.2.3"}},
```suggestion
                    "dependencies": {poetry.package.pretty_name: {"version": "1.2.3"}},
```

This way, the risk of accidentally making the test useless is reduced.

2022-12-18 12:31 UTC, radoering commented on tests/test_exporter.py
> +def test_exporter_can_export_requirements_txt_with_circular_dependency(
maybe

```suggestion
def test_exporter_can_export_requirements_txt_with_circular_root_dependency(
```

At the moment, it's not clear from its name that the focus of the test is a circular dependency _on the root package_.

2023-01-06 16:50 UTC, brechtm commented
Thanks for your suggestions, @ radoering. I have included the changes in my last commit.

2023-01-07 12:22 UTC, radoering approved these changes

2023-01-07 12:22 UTC, merged