fix: update import of deprecated repository modules
python-poetry/poetry-plugin-export pull request #151
Opened 2022-10-14 19:36 UTC by b-kamphorst

Depends on https://github.com/python-poetry/poetry/pull/6803.

2022-10-31 16:04 UTC, radoering requested changes
Can you make the imports forward compatible please? The scheme is try "new import" except "old import". Proposals below. You probably have to add some "type: ignore" or similar to satisfy mypy and flake8.

2022-10-31 16:04 UTC, radoering commented on src/poetry_plugin_export/exporter.py
> +from poetry.repositories.http_repository import HTTPRepository
```suggestion
try:
    from poetry.repositories.http_repository import HTTPRepository
except ImportError:
    from poetry.repositories.http import HTTPRepository
```

2022-10-31 16:04 UTC, radoering commented on tests/conftest.py
> +from poetry.repositories import RepositoryPool
```suggestion
try:
    from poetry.repositories import RepositoryPool
except ImportError:
    from poetry.repositories import Pool as RepositoryPool
```

2022-10-31 20:57 UTC, b-kamphorst commented
> Can you make the imports forward compatible please? The scheme is try "new import" except "old import". Proposals below. You probably have to add some "type: ignore" or similar to satisfy mypy and flake8.

Indeed, the current PR is valid only for `"poetry = ^1.3.0"` so that it is valid only after poetry 1.3.0 is released. I have made it backwards compatible in the way you describe so that we can release it already. If this PR is released only after the release of poetry 1.3.0, you may consider dropping the last commit (and require `poetry = ^1.3.0`).

2022-11-01 10:54 UTC, radoering commented
Yeah, if poetry-plugin-export and poetry would not be so closely coupled we could just wait. Unfortunately, we are still delivering poetry-plugin-export with poetry. (We intend to stop doing this. Another maintainer has already created a proof-of-concept on how to proceed in a gracefully way but he hasn't been available lately.) That's why we want to release a version of poetry-plugin-export that can be delivered with poetry 1.3 and will not trigger a deprecation warning.

2022-11-01 10:54 UTC, radoering approved these changes

2022-11-01 10:55 UTC, merged