Add a '--all-extras' option
python-poetry/poetry-plugin-export pull request #241
Opened 2023-10-19 07:43 UTC by pouillon

In my team, we are exporting the dependencies of some of our packages with the information from all extras to make sure that we have the same environment for different test and deployment scenarios. With time, we have been adding more extras and have had to update our configurations each time there is a new extra.

With this option, we don't have to care anymore about the extras explicitly and know that we'll always have the information we need correctly exported. We hope that this would be useful enough for other packages to be integrated into the official version of this plugin.

2023-10-19 11:28 UTC, dimbleby commented
#105

2023-10-29 16:09 UTC, radoering requested changes

2023-10-29 16:09 UTC, radoering commented on src/poetry_plugin_export/command.py
> +            }
mypy is failing here. Maybe, it's enough to insert `extras: Iterable[NormalizedName]` before the `if`.

2023-10-30 15:34 UTC, radoering approved these changes
I decided to apply the review feedback myself so I can include this feature in the next release without having to wait. 🙂

2023-10-30 15:34 UTC, merged

2023-10-30 15:36 UTC, pouillon commented on src/poetry_plugin_export/command.py
> +        option("all-extras", None, "Include all sets of extra dependencies."),
Thanks for the clarification. I had put it at the end because it was a new option. It seems that someone already did the change.

2023-10-30 15:36 UTC, pouillon commented
Thank you for merging this.