Add an all-groups option to export such that export will handle exporting all groups
python-poetry/poetry-plugin-export pull request #294
Opened 2024-08-16 20:50 UTC by Jiafi

Add an `--all-groups` options to the exported such that users can export all the groups in the pyproject.toml file.

Also adds some error handling when it is used in conjunction with the `--with` flag.

2024-08-16 20:52 UTC, jrouly approved these changes

2024-08-24 12:01 UTC, radoering requested changes
LGTM. I would just change the wording of the description and we should add the new option to the [readme](https://github.com/python-poetry/poetry-plugin-export/blob/main/README.md) and the [docs](https://github.com/python-poetry/poetry-plugin-export/blob/main/docs/_index.md).

2024-08-26 17:26 UTC, Jiafi commented on src/poetry_plugin_export/command.py
> +        option("all-groups", None, "Include all sets of extra groups"),
updated to use your verbage and used that in the docs as well

2024-09-01 09:33 UTC, radoering approved these changes

2024-09-01 09:34 UTC, merged